#!/usr/bin/env bash

PICTURES="pictures/"
OUTPUT="output"
EXE="../build/serial"
rm -rf "$OUTPUT"

operations=(
  "-reverse"
  "-brightness 40"
  "-contrast 40"
  "-rgb2grey 80"
  "-grey2rgb"
  "-rgb2bw"
  "-rgb2sepia"
  "-rotate -left"
  "-rotate -right"
  "-zoom"
  "-scale 2"
  "-blur 90"
)

for op in "${operations[@]}"; do
  op_dir="$OUTPUT/${op//[ -]/}"
  mkdir -p "$op_dir"
  perf record --output="$op_dir/perf.data" \
    -g --call-graph=dwarf -- "$EXE" "$PICTURES" "$op_dir/" $op

  if [ $? -ne 0 ]; then
    echo "Operation $op failed." >&2
    read -p "Press Enter to continue..."
  fi
done
