#!/usr/bin/env bash
PICTURES="${PICTURES:-test/pictures.small}"
OUTPUT="output/${PICTURES}"
rm -rf "$OUTPUT"

operations=(
  "-reverse"
  "-brightness 40"
  "-contrast 40"
  "-rgb2grey 80"
  "-grey2rgb"
  "-rgb2bw"
  "-rgb2sepia"
  "-rotate -left"
  "-rotate -right"
  "-zoom"
  "-scale 2"
  "-blur 90"
)


function run_test() {
  local exe="$1"
  for op in "${operations[@]}"; do
    op_dir="$OUTPUT/$(basename $exe)/${op//[ -]/}"
    mkdir -p "$op_dir"
    perf record --output="$op_dir/perf.data" \
      -g --call-graph=dwarf -- "$exe" "$PICTURES/" "$op_dir/" $op


    if [ $? -ne 0 ]; then
      echo "Operation $op failed." >&2
      read -p "Press Enter to continue..."
    fi
  done
}

run_test "./serial"
run_test "./parallel"
