#!/usr/bin/env bash
PICTURES="${PICTURES:-test/pictures.large}"
OUTPUT="output/${PICTURES}"
rm -rf "$OUTPUT"

operations=(
  "-reverse"
  "-brightness 40"
  "-contrast 40"
  "-rgb2grey 80"
  "-grey2rgb"
  "-rgb2bw"
  "-rgb2sepia"
  "-rotate -left"
  "-rotate -right"
  "-zoom"
  "-scale 2"
  "-blur 90"
)

function run_test() {
  local exe="$1"
  for op in "${operations[@]}"; do
    op_dir="$OUTPUT/$(basename $exe)/${op//[ -]/}"
    mkdir -p "$op_dir"
    "$exe" "$PICTURES/" "$op_dir/" $op


    if [ $? -ne 0 ]; then
      echo "Operation $op failed." >&2
      read -p "Press Enter to continue..."
    fi
  done
}

run_test "./serial"
run_test "./parallel"

for op in "${operations[@]}"; do
    op_dir_serial="$OUTPUT/serial/${op//[ -]/}"
    op_dir_parallel="$OUTPUT/parallel/${op//[ -]/}"
    for file in "$op_dir_serial"/*; do
      filename=$(basename "$file")
      file_parallel="$op_dir_parallel/$filename"
      if [ -f "$file_parallel" ]; then
        if ! diff -q "$file" "$file_parallel" > /dev/null; then
          echo "Difference found in $op: $filename"
        fi
      else
        echo "File missing in parallel: $file_parallel"
      fi
    done
done
